package KieRule

dialect "mvel"
import com.journaldev.spring.Order;
import com.journaldev.spring.model.Message;
import java.util.*;
import com.journaldev.spring.model.*;

global List<Message> messageList;
global Map<String, Message> mapResult;

rule "CD Maturity Reminder Banner Message"
    when
        accountObj : Account(accountType == "CDA" && statuCode == "IN_GRACE")
    then
        Message message = new Message();
        message.setMessageId("cd.maturity.reminder");
        message.setMessage("Your CDA account matured, take action with 7 days.");
        mapResult.put(accountObj.getAccountId(), message);
end;
